### PR TITLE
Fix profanity nodes and bad class serializing

### PR DESCRIPTION
**Pull request by Screaper91**
- Fixes ProfanityNodes crashing client with filter enabled
- Fixes chat not censoring player names
- Fixes FormattedTextNodes being defined as classes instead of types

### CODE REVIEW

**Review by zunda-arrow — COMMENTED** [review]
I don't understand the reason for this. Normally I appreciate removing classes for a more functional style, but this does not make sense here. We had nicely scoped constructors in my previous version, which are now gone. Removing these namepsaces reduces readability. It also takes longer to type these nodes which doesn't matter if it provides an advantage, but this doesn't. Additionally you broke all the tests.  Those were there for a reason.

To me, It feels like you are trying to follow the best style guide for typescript without thinking about the impact it has on the code. Please explain your case on why this is an improvement. Why does this make the code more maintainable? Why does this make the code easier to write? What was bad?

**Comment by alicetouhou** [comment]
Yeah... sorry I misread this and thought your changes were much smaller than they actually were due to the comments you left.

**Comment by zunda-arrow** [comment]
Okay I see now. The helper methods exist because of ts shenanigans. Man fuck this language.
My bad for failing to test it tho. You gotta work around your tools lol.

**Comment by Screaper91** [comment]
Once all refactors are done, I'll learn and understand the new style so I don't submit stuff that fails the unit tests. I only realized that errors when the profanity filter was active were caused by the sockets used being unable to receive non-serialized classes and needed attention before the battle log changes were merged.

**Pull request merged**
